name: Docker Builder for python-helloworld

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v2
      - name: Set up Qemu
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to the Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DH_USERNAME}}
          password: ${{secrets.DH_PASSWORD}}
      - name: Build and push the image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{secrets.DH_REPO}}/python-helloworld:latest
